Should clearly identify failed step
Introduced modifications to clearly identify failing steps.
JUnit filnal resport will now look similar to:

```text
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.397 sec - in com.github.bmsantos.maven.cola.ReportColaTest

Results :

Failed tests:
  FailedExamplesColaTest.An example feature : Should parse examples - projection 0:-1
	Error: Failed to call step: Then I should have <left> cucumbers with projection values: {"start":"12","left":"7h","eat":"5"}
	Cause: For input string: "7h"
  FailedExamplesColaTest.An example feature : Should parse examples - projection 1:-1
	Error: Failed step: Then I should have <left> cucumbers with projection values: {"start":"20","left":"19","eat":"5"}
	Cause:
Expected: <19>
     but: was <15>

Tests run: 35, Failures: 2, Errors: 0, Skipped: 0
```

Issue #44